pages:
  stage: deploy
  tags:
    - prod-gke-runner
  image: node:22-alpine
  script:
    - npm ci
    - npm run build
    - mkdir -p public
    - cp -r dist/. public/
  artifacts:
    paths:
      - public
  only:
    - master
