pages:
  stage: deploy
  tags:
    - prod-docker-docker-autoscaler-runner
  image: alpine:latest
  script:
    - mkdir -p public
    - cp -r dist/. public/
  artifacts:
    paths:
      - public
  only:
    - master
